spring:
  datasource:
    url: jdbc:mysql://localhost:3307/car?useSsL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
