spring:
  datasource:
    url: jdbc:mysql://localhost:3307/car?useSsL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 1
      host: 127.0.0.1
      port: 6379
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 10
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池最大连接数
          max-active: 200

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
