CREATE TABLE USER
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME       VARCHAR(100),
    TEL            VARCHAR(20) UNIQUE,
    AVATAR_URL     VARCHAR(1024),
    ADDRESS        VARCHAR(1024),
    ROLE_ID        BIGINT,
    WX_OPEN_ID     varchar(1024),
    WX_SESSION_KEY varchar(1024),
    BIRTHDAY       TIMESTAMP,
    SEX            TINYINT,
    PASSWORD       VARCHAR(1024),
    BALANCE        DECIMAL(12, 2),
    CREATED_AT     TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT     TIMESTAMP NOT NULL DEFAULT NOW()
);